// <auto-generated />
using System;
using Kart.AiAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kart.AiAssistant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AiAssistantDbContext))]
    [Migration("20260818170009_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kart.AiAssistant.Infrastructure.Persistence.AuditRecordRow", b =>
                {
                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.Property<bool>("ClarificationIssued")
                        .HasColumnType("boolean")
                        .HasColumnName("clarification_issued");

                    b.Property<string>("ClarificationQuestion")
                        .HasColumnType("text")
                        .HasColumnName("clarification_question");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("DataSource")
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<string>("ErrorsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("errors");

                    b.Property<long?>("ExecutionTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("execution_time_ms");

                    b.Property<string>("FinalResponseSummary")
                        .HasColumnType("text")
                        .HasColumnName("final_response_summary");

                    b.Property<string>("GroundingCheckResult")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grounding_check_result");

                    b.Property<bool?>("IsProvisional")
                        .HasColumnType("boolean")
                        .HasColumnName("is_provisional");

                    b.Property<long?>("LlmExplainLatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("llm_explain_latency_ms");

                    b.Property<long?>("LlmPlanLatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("llm_plan_latency_ms");

                    b.Property<string>("LlmTokenUsageJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("llm_token_usage");

                    b.Property<string>("QueryParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("query_parameters");

                    b.Property<DateOnly?>("ReconciledThrough")
                        .HasColumnType("date")
                        .HasColumnName("reconciled_through");

                    b.Property<string>("ResolvedIntentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resolved_intent");

                    b.Property<int?>("ResultSize")
                        .HasColumnType("integer")
                        .HasColumnName("result_size");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("ToolsInvokedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("tools_invoked");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserQuestion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_question");

                    b.HasKey("TurnId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_ai_assistant_audit_records_timestamp");

                    b.HasIndex("ConversationId", "Timestamp")
                        .HasDatabaseName("idx_ai_assistant_audit_records_conversation");

                    b.HasIndex("UserId", "Timestamp")
                        .HasDatabaseName("idx_ai_assistant_audit_records_user");

                    b.ToTable("ai_assistant_audit_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
